"""
logger.py
Writes human-readable daily logs and keeps README stats updated.
"""

import json
import os
from datetime import datetime, timezone, date


LOG_DIR  = "data/logs"
README   = "README.md"


def write_daily_log(entry: dict, run_number: int):
    """Append this run's learning to today's markdown log file."""
    os.makedirs(LOG_DIR, exist_ok=True)

    today    = date.today().isoformat()
    log_file = f"{LOG_DIR}/{today}.md"
    now      = datetime.now(timezone.utc).strftime("%H:%M UTC")

    # Create header if file is new
    if not os.path.exists(log_file):
        with open(log_file, "w") as f:
            f.write(f"# 🧠 Learning Log — {today}\n\n")
            f.write(f"Auto-generated by Gemini Coding Brain\n\n")
            f.write("---\n")

    with open(log_file, "a") as f:
        f.write(f"\n## Run #{run_number} — {now}\n\n")
        f.write(f"**Topic:** {entry['topic']}  \n")
        f.write(f"**Category:** `{entry.get('category', 'N/A')}`  \n")
        f.write(f"**Difficulty:** `{entry.get('difficulty', 'N/A')}`  \n")
        f.write(f"**Language:** `{entry.get('language', 'N/A')}`  \n\n")

        f.write(f"### Summary\n{entry.get('summary', '')}\n\n")

        if entry.get("key_points"):
            f.write("### Key Points\n")
            for point in entry["key_points"]:
                f.write(f"- {point}\n")
            f.write("\n")

        if entry.get("code_example"):
            ex   = entry["code_example"]
            lang = ex.get("language", "")
            f.write(f"### Code Example\n*{ex.get('description', '')}*\n\n")
            f.write(f"```{lang}\n{ex.get('correct', '')}\n```\n\n")
            if ex.get("wrong"):
                f.write(f"**❌ Common mistake:**\n```{lang}\n{ex['wrong']}\n```\n\n")

        if entry.get("best_practices"):
            f.write("### Best Practices\n")
            for bp in entry["best_practices"]:
                f.write(f"- ✅ {bp}\n")
            f.write("\n")

        if entry.get("interview_questions"):
            f.write("### Interview Questions\n")
            for qa in entry["interview_questions"]:
                f.write(f"**Q:** {qa.get('question', '')}  \n")
                f.write(f"**A:** {qa.get('answer', '')}  \n\n")

        f.write("---\n")

    print(f"📝 Log written → {log_file}")


def update_readme(knowledge: dict):
    """Rewrite the stats section of README.md."""
    meta    = knowledge.get("meta", {})
    entries = knowledge.get("entries", [])

    total   = meta.get("total_runs", 0)
    updated = meta.get("last_updated", "N/A")

    # Count categories
    category_counts: dict[str, int] = {}
    for e in entries:
        cat = e.get("category", "unknown")
        category_counts[cat] = category_counts.get(cat, 0) + 1

    category_table = "\n".join(
        f"| {cat} | {count} |"
        for cat, count in sorted(category_counts.items(), key=lambda x: -x[1])
    )

    # Last 5 topics
    recent_topics = "\n".join(
        f"- `{e['topic']}`"
        for e in entries[-5:][::-1]
    )

    stats_block = f"""## 📊 Live Stats

| Metric | Value |
|---|---|
| Total Topics Learned | **{total}** |
| Last Updated | `{updated}` |
| Dataset Size | `{len(entries)} entries` |

## 📂 Categories Learned

| Category | Topics |
|---|---|
{category_table}

## 🕐 Last 5 Topics Learned

{recent_topics}

"""

    # Read existing README or create skeleton
    if os.path.exists(README):
        with open(README) as f:
            content = f.read()

        # Replace between markers
        start_marker = "<!-- STATS_START -->"
        end_marker   = "<!-- STATS_END -->"

        if start_marker in content and end_marker in content:
            before = content.split(start_marker)[0]
            after  = content.split(end_marker)[1]
            content = f"{before}{start_marker}\n{stats_block}{end_marker}{after}"
        else:
            # Markers don't exist — append stats
            content += f"\n{start_marker}\n{stats_block}{end_marker}\n"

        with open(README, "w") as f:
            f.write(content)
    else:
        # Create fresh README
        with open(README, "w") as f:
            f.write(f"""# 🧠 Gemini Coding Brain

An autonomous AI agent that learns coding concepts daily using Gemini API
and commits its growing knowledge base to GitHub automatically.

<!-- STATS_START -->
{stats_block}<!-- STATS_END -->

## 🚀 How It Works

1. GitHub Actions triggers the agent every ~72 minutes (20x per day)
2. Gemini learns a new coding topic deeply and structures it as JSON
3. The knowledge base grows automatically with every run
4. Daily markdown logs track everything learned each day
5. The dataset is exported in fine-tuning format for future model training

## 📁 Structure

```
data/
  knowledge_base.json   ← main growing dataset
  topics_queue.json     ← queue of topics to learn
  logs/YYYY-MM-DD.md    ← daily learning logs
export/
  finetune_ready.jsonl  ← ready for model fine-tuning later
```
""")

    print("📄 README updated")
